---
passwd:
  users:
    - name: core
      groups:
        - sudo
        - docker
systemd:
  units:
    - name: "coreos-metadata-sshkeys@.service"
      enabled: true
      dropins:
        - name: "use-script.conf"
          contents: |
            [Service]
            ExecStart=
            ExecStart=/usr/share/oem/scaleway-coreos-custom-metadata ssh-keys %i
    - name: "coreos-metadata.service"
      dropins:
        - name: "use-script.conf"
          contents: |
            [Service]
            # Empty ExecStart= prevents the previously defined ExecStart from running
            ExecStart=
            ExecStartPre=/usr/share/oem/scaleway-coreos-custom-metadata
