---
passwd:
  users:
    - name: core
      groups:
        - sudo
        - docker
storage:
  files:
    - filesystem: "root"
      path: "/opt/scaleway-coreos-custom-metadata"
      mode: 0750
      contents:
        remote:
          url: "https://github.com/jbonachera/scaleway-coreos-custom-metadata/releases/download/v0.0.2/scaleway-coreos-custom-metadata"
systemd:
  units:
    - name: "coreos-metadata.service"
      dropins:
        - name: "use-script.conf"
          contents: |
            [Service]
            # Empty ExecStart= prevents the previously defined ExecStart from running
            ExecStart=
            ExecStartPre=/opt/scaleway-coreos-custom-metadata
            ExecStart=/usr/bin/update-ssh-keys -u core
    - name: scw-signal-booted.service
      enabled: true
      contents: |
        [Unit]
        Description=Signal successful boot to Scaleway control plane
        Requires=network-online.target coreos-metadata.service
        After=network.target network-online.target coreos-metadata.service
        [Service]
        Type=oneshot
        ExecStart=/usr/bin/curl -s --fail -XPATCH -H 'Content-Type: application/json' http://169.254.42.42/state -d '{"state_detail": "booted"}' -o /dev/null
        [Install]
        WantedBy=basic.target
