#!/bin/sh

echo ":: transpiliting config.yaml"
/usr/bin/container-linux-config-transpiler --in-file config.yaml > ignition.json
if [ "$?" -gt 0 ]; then
  exit 1
fi
secrets_file_opt=""
if [ -r /srv/secrets.json ]; then
secrets_file_opt="-var-file=/srv/secrets.json"
fi

echo ":: running packer"
/bin/packer version
/bin/packer build $secrets_file_opt packer.json
